### ISSUE TITLE
Does it make sense to create a separate module for routing?

### ISSUE THREAD

**Issue by HansS** [juristr/video-your-first-ng2-app#1]
to my understanding a module encapsulates all components, directives or pipes of a feature area.
Modules also serve for being able to lazy load a part of your application.
A module for routing alone does not make sense for me, routing is part of a feature module and does not stand for it alone. If you have are not using modules then you have onle one module the root module in most cases the app.module.

**Comment by juristr** [comment]
Hey. Yes, I totally agree with your point of view. Personally I am also mote proponent to placing the routing information directly into each feature module s.t. it can be managed there as child routes.

The [official docs also propose the routing module pattern](https://angular.io/docs/ts/latest/guide/router.html#!#routing-module) which is an alternative way of structuring your routes and may make sense when routing gets really complex and when you want it to be easily findable in a single place rather than scattered throughout your entire app.

But to be honest I have to make some more experiments and try both of  them in order to have a more clear opinion on this matter. :)
